// Generated by CoffeeScript 1.12.2
(function() {
  Template.hello.events({
    'click #basicSubmit': function(event, instance) {
      Meteor.call('basicSubmit');
    },
    'click #repeatSubmit': function(event, instance) {
      Meteor.call('repeatSubmit');
    }
  });

}).call(this);

//# sourceMappingURL=main.js.map
