// Generated by CoffeeScript 1.12.2
(function() {
  var multipleQueue;

  multipleQueue = JobCollection('multipleQueue');

  Meteor.startup(function() {
    multipleQueue.startJobServer();
    multipleQueue.processJobs('sendEmail', {
      pollInterval: 1 * 1000
    }, function(job, callback) {
      console.log('SEND Email', job.data);
      job.done();
      callback();
    });
    multipleQueue.processJobs('archiveEmail', {
      pollInterval: 1 * 1000
    }, function(job, callback) {
      console.log('ARCHIVE Email', job.data);
      job.done();
      callback();
    });
  });

  Meteor.methods({
    triggerMultiple: function() {
      var archiveJob, sendJob;
      sendJob = new Job(multipleQueue, 'sendEmail', {
        address: 'bozo@clowns.com',
        subject: 'Critical rainbow hair shortage',
        message: 'LOL; JK, KThxBye.'
      });
      archiveJob = new Job(multipleQueue, 'archiveEmail', {
        mydata: 'data'
      });
      sendJob.save(function(error, res) {
        console.log('sendJob successfully saved');
        if (res) {
          console.log('id is : ', res);
          archiveJob.depends([sendJob]).save();
        }
      });
    }
  });

}).call(this);

//# sourceMappingURL=depends.js.map
