// Generated by CoffeeScript 1.12.2
(function() {
  var waitQueue;

  waitQueue = JobCollection('waitQueue');

  Meteor.startup(function() {
    waitQueue.startJobServer();
    waitQueue.processJobs('callLongWaitTask', {
      pollInterval: 1 * 1000
    }, function(job, callback) {
      console.log('Job worker started, with .processJobs() ');
      Meteor.call('longWait', function(error, res) {
        console.log('longWait Method callback');
        if (res) {
          console.log(res);
          job.done();
        }
        if (error) {
          console.log(error);
          job.cancel();
        }
      });
      callback();
    });
  });

  Meteor.methods({
    triggerLongWaitTask: function() {
      console.log('Sumbitting task type "callLongWaitTask" ');
      Job(waitQueue, 'callLongWaitTask', {}).save();
    },
    longWait: function() {
      var fut, milliseconds;
      console.log('Called Meteor method \'longWait\'. This will take some time to completed.');
      milliseconds = 30000;
      fut = new Future;
      Meteor.setTimeout((function() {
        fut['return']('The return is delayed :' + milliseconds + 'ms');
      }), milliseconds);
      return fut.wait();
    }
  });

}).call(this);

//# sourceMappingURL=longWait.js.map
