// Generated by CoffeeScript 1.12.2
(function() {
  var theQueue;

  theQueue = JobCollection('myJobQueue');

  Meteor.startup(function() {
    theQueue.startJobServer();
    theQueue.processJobs('echo', {
      pollInterval: 1 * 1000
    }, function(job, callback) {
      console.log('job process triggered');
      console.log(job.data);
      job.done();
      callback();
    });
  });

  Meteor.methods({
    basicSubmit: function() {
      console.log('Sumbitting test job "Echo" ');
      Job(theQueue, 'echo', {
        message: 'Hello, is there anybody in here?'
      }).save();
    },
    repeatSubmit: function() {
      var newEchoJob;
      console.log('Sumbitting test job "Echo" ');
      newEchoJob = new Job(theQueue, 'echo', {
        message: 'Hello, is there anybody in here?'
      });
      newEchoJob.repeat({
        repeats: 2,
        wait: 10
      });
      newEchoJob.save();
    }
  });

}).call(this);

//# sourceMappingURL=simplest.js.map
