theQueue = JobCollection('myJobQueue')


Meteor.startup ->
  # Start the myJobs queue running
  theQueue.startJobServer()
  # Start processing the jobs in the queue for type 'echo'
  theQueue.processJobs 'echo', { pollInterval: 1 * 1000 }, (job, callback) ->
    # ##### THIS IS WHERE THE WORK GETS DONE #####//
    console.log 'job process triggered'
    # Only called when there is a valid job
    #job.data is a data object the developer can pass when submitting up a new job.
    console.log job.data
    job.done()
    # Mark the job done
    callback()
    # TODO: what is this? Can the dev modify this?
    return
  return


Meteor.methods
  basicSubmit: ->
    console.log 'Sumbitting test job "Echo" '
    Job(theQueue, 'echo', message: 'Hello, is there anybody in here?').save()
    return
  repeatSubmit: ->
    console.log 'Sumbitting test job "Echo" '
    newEchoJob = new Job(theQueue, 'echo', message: 'Hello, is there anybody in here?')
    # Set some properties of the job
    newEchoJob.repeat
      repeats: 2
      wait: 10
    # submit the job, will set the status to 'waiting'.
    newEchoJob.save()
    return

# ---
# generated by js2coffee 2.2.0